import { useCallback, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { Screen } from '../../src/components/Screen';
import { colors } from '../../src/theme';

type Range = '1W' | '1M' | '6W' | '3M' | 'ALL' | 'CUSTOM';
type HistoryRow = { id: string; started_at: string; status: string; rating: string | null; distance_value: number | null; distance_unit: string; notes: string | null; modified: number; sort_order: number };
const rangeDays: Record<Exclude<Range, 'ALL' | 'CUSTOM'>, number> = { '1W': 7, '1M': 30, '6W': 42, '3M': 90 };
const dotColor = (item: HistoryRow) => item.status === 'ended_early' ? colors.red : item.modified ? '#D19A00' : colors.green;

export default function ProgressScreen() {
  const db = useSQLiteContext();
  const [range, setRange] = useState<Range>('1M');
  const [history, setHistory] = useState<HistoryRow[]>([]);
  const [currentSchedule, setCurrentSchedule] = useState(1);
  const [showHistory, setShowHistory] = useState(true);
  const [customStart, setCustomStart] = useState('');
  const [customEnd, setCustomEnd] = useState('');
  const load = useCallback(async () => { const current = await db.getFirstAsync<{ sort_order: number }>("SELECT s.sort_order FROM schedules s JOIN app_metadata m ON m.value = s.id WHERE m.key = 'current_schedule_id'"); const rows = await db.getAllAsync<HistoryRow>('SELECT w.id, w.started_at, w.status, w.rating, w.distance_value, w.distance_unit, w.notes, w.modified, s.sort_order FROM workouts w JOIN schedules s ON s.id = w.schedule_id WHERE w.deleted_at IS NULL ORDER BY w.started_at DESC'); setCurrentSchedule(current?.sort_order ?? 1); setHistory(rows); }, [db]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const visibleHistory = useMemo(() => { if (range === 'ALL') return history; if (range === 'CUSTOM') { const start = customStart ? new Date(`${customStart}T00:00:00`).getTime() : -Infinity; const end = customEnd ? new Date(`${customEnd}T23:59:59`).getTime() : Infinity; return history.filter((item) => { const time = new Date(item.started_at).getTime(); return time >= start && time <= end; }); } return history.filter((item) => new Date(item.started_at).getTime() >= Date.now() - rangeDays[range] * 24 * 60 * 60 * 1000); }, [history, range, customStart, customEnd]);
  const deleteWorkout = (id: string) => Alert.alert('Delete this workout?', 'It will be hidden from the app but retained in your JSON backup.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => { void db.runAsync("UPDATE workouts SET deleted_at = ? WHERE id = ?", new Date().toISOString(), id).then(load); } }]);
  return <Screen><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>PROGRESS</Text><Text style={styles.title}>Schedule {currentSchedule} of 17</Text><Text style={styles.subtitle}>Your jogging progression</Text><View style={styles.rangeRow}>{(['1W', '1M', '6W', '3M', 'ALL', 'CUSTOM'] as Range[]).map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.range, range === item && styles.rangeSelected]}><Text style={[styles.rangeText, range === item && styles.rangeTextSelected]}>{item}</Text></Pressable>)}</View>{range === 'CUSTOM' && <View style={styles.customRow}><TextInput value={customStart} onChangeText={setCustomStart} placeholder="YYYY-MM-DD" placeholderTextColor={colors.muted} style={styles.dateInput} /><Text style={styles.to}>to</Text><TextInput value={customEnd} onChangeText={setCustomEnd} placeholder="YYYY-MM-DD" placeholderTextColor={colors.muted} style={styles.dateInput} /></View>}<View style={styles.chart}><View style={styles.yLabels}><Text style={styles.axisLabel}>17</Text><Text style={styles.axisLabel}>9</Text><Text style={styles.axisLabel}>1</Text></View><View style={styles.plot}>{visibleHistory.slice().reverse().map((item, index) => <View key={item.id} style={[styles.dot, { left: `${visibleHistory.length < 2 ? 50 : (index / (visibleHistory.length - 1)) * 92 + 4}%`, bottom: `${((item.sort_order - 1) / 16) * 82 + 8}%`, backgroundColor: dotColor(item) }]} />)}</View></View><View style={styles.legend}><Legend color={colors.green} text="Completed" /><Legend color={colors.red} text="Ended early" /><Legend color="#D19A00" text="Modified" /></View><Pressable onPress={() => setShowHistory(!showHistory)} style={styles.historyButton}><Text style={styles.historyButtonText}>{showHistory ? 'HIDE HISTORY' : 'SHOW HISTORY'}</Text></Pressable>{showHistory && (visibleHistory.length === 0 ? <Text style={styles.empty}>No workouts recorded yet.</Text> : visibleHistory.map((item) => <View key={item.id} style={styles.historyRow}><View style={[styles.statusDot, { backgroundColor: dotColor(item) }]} /><View style={styles.historyCopy}><Text style={styles.historyDate}>{new Date(item.started_at).toLocaleDateString()}</Text><Text style={styles.historyMeta}>Schedule {item.sort_order} · {item.status === 'ended_early' ? 'Ended early' : item.modified ? 'Modified' : 'Completed'}</Text>{item.notes && <Text style={styles.notes}>{item.notes}</Text>}<Pressable onPress={() => deleteWorkout(item.id)}><Text style={styles.deleteText}>DELETE ENTRY</Text></Pressable></View><View style={styles.historyRight}><Text style={styles.distance}>{item.distance_value == null ? '—' : `${item.distance_value.toFixed(2)} ${item.distance_unit}`}</Text><Text style={styles.rating}>{item.rating?.replace('_', ' ') ?? '—'}</Text></View></View>))}</ScrollView></Screen>;
}

function Legend({ color, text }: { color: string; text: string }) { return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]} /><Text style={styles.legendText}>{text}</Text></View>; }

const styles = StyleSheet.create({ content: { paddingTop: 14, paddingBottom: 36 }, eyebrow: { color: colors.purple, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, title: { color: colors.ink, fontSize: 28, fontWeight: '800', marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 15, marginTop: 5 }, rangeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 24 }, range: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingVertical: 8, paddingHorizontal: 12 }, rangeSelected: { backgroundColor: colors.purple, borderColor: colors.purple }, rangeText: { color: colors.muted, fontSize: 12, fontWeight: '800' }, rangeTextSelected: { color: colors.surface }, customRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 }, dateInput: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: 10, color: colors.ink, paddingHorizontal: 10, paddingVertical: 9, fontSize: 12 }, to: { color: colors.muted }, chart: { height: 210, marginTop: 24, flexDirection: 'row', borderBottomWidth: 1, borderLeftWidth: 1, borderColor: colors.border }, yLabels: { width: 26, justifyContent: 'space-between', alignItems: 'flex-end', paddingVertical: 4 }, axisLabel: { color: colors.muted, fontSize: 11 }, plot: { flex: 1, position: 'relative', marginLeft: 8 }, dot: { width: 13, height: 13, borderRadius: 7, position: 'absolute' }, legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginTop: 14 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 }, legendDot: { width: 8, height: 8, borderRadius: 4 }, legendText: { color: colors.muted, fontSize: 12 }, historyButton: { alignSelf: 'flex-start', marginTop: 26, paddingVertical: 8 }, historyButtonText: { color: colors.purple, fontSize: 12, fontWeight: '900', letterSpacing: 1 }, empty: { color: colors.muted, textAlign: 'center', marginTop: 24 }, historyRow: { flexDirection: 'row', alignItems: 'flex-start', borderTopWidth: 1, borderColor: colors.border, paddingVertical: 15 }, statusDot: { width: 11, height: 11, borderRadius: 6, marginTop: 4 }, historyCopy: { flex: 1, paddingLeft: 10 }, historyDate: { color: colors.ink, fontSize: 15, fontWeight: '800' }, historyMeta: { color: colors.muted, fontSize: 13, marginTop: 4, textTransform: 'capitalize' }, notes: { color: colors.ink, fontSize: 13, marginTop: 6 }, deleteText: { color: colors.red, fontSize: 11, fontWeight: '900', marginTop: 8 }, historyRight: { alignItems: 'flex-end', paddingLeft: 8 }, distance: { color: colors.ink, fontSize: 14, fontWeight: '800' }, rating: { color: colors.muted, fontSize: 12, marginTop: 5, textTransform: 'capitalize' } });
