import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { useSQLiteContext } from 'expo-sqlite';
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { Screen } from '../../src/components/Screen';
import { colors } from '../../src/theme';

const version = '1.0.0';

export default function SettingsScreen() {
  const db = useSQLiteContext();
  const [voice, setVoice] = useState(true);
  const [haptics, setHaptics] = useState(true);
  const [volume, setVolume] = useState(1);
  const [unit, setUnit] = useState<'mi' | 'km'>('mi');
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const rows = await db.getAllAsync<{ key: string; value: string }>("SELECT key, value FROM app_metadata WHERE key IN ('voice_cues_enabled', 'haptics_enabled', 'cue_volume', 'distance_unit')"); const values = Object.fromEntries(rows.map((row) => [row.key, row.value])); setVoice(values.voice_cues_enabled !== '0'); setHaptics(values.haptics_enabled !== '0'); setVolume(Number(values.cue_volume ?? 1)); setUnit(values.distance_unit === 'km' ? 'km' : 'mi'); }, [db]);
  useEffect(() => { load(); }, [load]);
  const setPreference = async (key: string, value: string) => { await db.runAsync('INSERT OR REPLACE INTO app_metadata (key, value) VALUES (?, ?)', key, value); };
  const saveVoice = (value: boolean) => { setVoice(value); void setPreference('voice_cues_enabled', value ? '1' : '0'); };
  const saveHaptics = (value: boolean) => { setHaptics(value); void setPreference('haptics_enabled', value ? '1' : '0'); };
  const adjustVolume = (delta: number) => { const next = Math.max(0, Math.min(1, Math.round((volume + delta) * 10) / 10)); setVolume(next); void setPreference('cue_volume', String(next)); };
  const changeUnit = (next: 'mi' | 'km') => { setUnit(next); void setPreference('distance_unit', next); };

  const createBackup = async () => { setBusy(true); try { const metadata = await db.getAllAsync<{ key: string; value: string }>('SELECT key, value FROM app_metadata'); const workouts = await db.getAllAsync('SELECT * FROM workouts'); const contents = JSON.stringify({ format: 'autolaufer', version: 1, exported_at: new Date().toISOString(), metadata, workouts }, null, 2); if (!FileSystem.cacheDirectory || !(await Sharing.isAvailableAsync())) throw new Error('File sharing is unavailable.'); const uri = `${FileSystem.cacheDirectory}autolaufer-backup-${Date.now()}.json`; await FileSystem.writeAsStringAsync(uri, contents, { encoding: FileSystem.EncodingType.UTF8 }); try { await Sharing.shareAsync(uri, { dialogTitle: 'Save Autoläufer Backup', mimeType: 'application/json', UTI: 'public.json' }); } finally { await FileSystem.deleteAsync(uri, { idempotent: true }); } } catch (error) { Alert.alert('Backup failed', error instanceof Error ? error.message : 'Unable to create backup.'); } finally { setBusy(false); } };

  const restoreBackup = async () => { const result = await DocumentPicker.getDocumentAsync({ type: 'application/json', copyToCacheDirectory: true, multiple: false }); if (result.canceled || !result.assets[0]) return; const contents = await FileSystem.readAsStringAsync(result.assets[0].uri); Alert.alert('Restore this backup?', 'Restoring will replace the current workout history and settings.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Restore', style: 'destructive', onPress: () => { void (async () => { setBusy(true); try { const parsed = JSON.parse(contents) as { format?: string; metadata?: { key: string; value: string }[]; workouts?: BackupWorkout[] }; if (parsed.format !== 'autolaufer' || !Array.isArray(parsed.workouts) || !Array.isArray(parsed.metadata)) throw new Error('This is not a valid Autoläufer backup.'); const backupWorkouts = parsed.workouts; const backupMetadata = parsed.metadata; await db.withTransactionAsync(async () => { await db.runAsync('DELETE FROM workouts'); for (const workout of backupWorkouts) { await db.runAsync('INSERT INTO workouts (id, schedule_id, started_at, ended_at, status, rating, distance_value, distance_unit, notes, modified, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', workout.id, workout.schedule_id, workout.started_at, workout.ended_at ?? null, workout.status, workout.rating ?? null, workout.distance_value ?? null, workout.distance_unit ?? 'mi', workout.notes ?? null, workout.modified ?? 0, workout.deleted_at ?? null); } for (const item of backupMetadata) await db.runAsync('INSERT OR REPLACE INTO app_metadata (key, value) VALUES (?, ?)', item.key, item.value); }); await load(); Alert.alert('Restore complete', 'Your backup was restored.'); } catch (error) { Alert.alert('Restore failed', error instanceof Error ? error.message : 'Unable to restore backup.'); } finally { setBusy(false); } })(); } }]); };

  return <Screen><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Settings</Text><Text style={styles.section}>WORKOUT CUES</Text><SettingRow label="Voice cues"><Switch value={voice} onValueChange={saveVoice} trackColor={{ false: colors.border, true: colors.purplePale }} thumbColor={voice ? colors.purple : colors.muted} /></SettingRow><SettingRow label="Haptic feedback"><Switch value={haptics} onValueChange={saveHaptics} trackColor={{ false: colors.border, true: colors.purplePale }} thumbColor={haptics ? colors.purple : colors.muted} /></SettingRow><View style={styles.row}><Text style={styles.label}>Cue volume</Text><View style={styles.volume}><Pressable onPress={() => adjustVolume(-0.1)} style={styles.volumeButton}><Text style={styles.volumeButtonText}>−</Text></Pressable><Text style={styles.volumeValue}>{Math.round(volume * 100)}%</Text><Pressable onPress={() => adjustVolume(0.1)} style={styles.volumeButton}><Text style={styles.volumeButtonText}>+</Text></Pressable></View></View><Text style={styles.section}>DISTANCE</Text><View style={styles.segment}><Pressable onPress={() => changeUnit('mi')} style={[styles.segmentButton, unit === 'mi' && styles.segmentSelected]}><Text style={[styles.segmentText, unit === 'mi' && styles.segmentTextSelected]}>Miles</Text></Pressable><Pressable onPress={() => changeUnit('km')} style={[styles.segmentButton, unit === 'km' && styles.segmentSelected]}><Text style={[styles.segmentText, unit === 'km' && styles.segmentTextSelected]}>Kilometers</Text></Pressable></View><Text style={styles.section}>DATA</Text><Pressable disabled={busy} onPress={createBackup} style={styles.action}><Text style={styles.actionText}>BACK UP DATA</Text></Pressable><Pressable disabled={busy} onPress={restoreBackup} style={styles.action}><Text style={styles.actionText}>RESTORE FROM BACKUP</Text></Pressable><Text style={styles.version}>Autoläufer · Version {version}</Text></ScrollView></Screen>;
}

function SettingRow({ label, children }: { label: string; children: React.ReactNode }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text>{children}</View>; }

type BackupWorkout = { id: string; schedule_id: string; started_at: string; ended_at?: string | null; status: string; rating?: string | null; distance_value?: number | null; distance_unit?: string; notes?: string | null; modified?: number; deleted_at?: string | null };

const styles = StyleSheet.create({ content: { paddingTop: 14, paddingBottom: 40 }, title: { color: colors.ink, fontSize: 30, fontWeight: '800' }, section: { color: colors.purple, fontSize: 12, fontWeight: '900', letterSpacing: 1.4, marginTop: 30, marginBottom: 8 }, row: { minHeight: 56, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, label: { color: colors.ink, fontSize: 16, fontWeight: '600' }, volume: { flexDirection: 'row', alignItems: 'center', gap: 14 }, volumeButton: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.purplePale, alignItems: 'center', justifyContent: 'center' }, volumeButtonText: { color: colors.purple, fontSize: 22, lineHeight: 25 }, volumeValue: { color: colors.ink, fontSize: 15, fontWeight: '800', minWidth: 42, textAlign: 'center' }, segment: { flexDirection: 'row', borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 3 }, segmentButton: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: 9 }, segmentSelected: { backgroundColor: colors.purple }, segmentText: { color: colors.muted, fontWeight: '800' }, segmentTextSelected: { color: colors.surface }, action: { borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: 18 }, actionText: { color: colors.purple, fontSize: 14, fontWeight: '900', letterSpacing: 0.6 }, version: { color: colors.muted, fontSize: 13, textAlign: 'center', marginTop: 34 } });
